import { Router } from "express";
import * as roomController from "../controller/room.controller.js";
import { requireRole } from "../middleware/roleMiddleware.js";
const router = Router();
router.get("/",requireRole("CEO", "ADMIN", "MANAGER","TEACHER"), roomController.getAll);
router.get("/:id",requireRole("CEO", "ADMIN", "MANAGER",), roomController.getById);
router.post("/",requireRole("CEO", "ADMIN", "MANAGER"), roomController.create);
router.put("/",requireRole("CEO", "ADMIN", "MANAGER",), roomController.update);
router.delete("/:id",requireRole("CEO", "ADMIN", "MANAGER",), roomController.deleteById);
export default router;
